<?php
/**
 * Export helpers.
 *
 * PDF and PNG export happen in the browser — see assets/js/export.js — so that
 * no server round trip and no external service is involved. This class covers
 * the plain-text format, which the admin screens and the assignment tools also
 * need, plus the file-name rules shared by every format.
 *
 * @package DesignProjectGenerator
 */

defined( 'ABSPATH' ) || exit;

/**
 * Text export and download handling.
 */
class DPG_Export {

	/**
	 * Hook into WordPress.
	 */
	public function __construct() {
		add_action( 'admin_post_dpg_export_assignment', array( $this, 'handle_assignment_download' ) );
	}

	/**
	 * Build a slug-based file name for a project.
	 *
	 * @param array  $project   Validated project.
	 * @param string $extension File extension without a dot.
	 * @return string
	 */
	public static function filename( array $project, $extension = 'txt' ) {
		$base = sanitize_title( ( isset( $project['client'] ) ? $project['client'] . ' ' : '' ) . 'project' );

		if ( '' === $base ) {
			$base = 'design-project';
		}

		return $base . '.' . preg_replace( '/[^a-z0-9]/', '', strtolower( $extension ) );
	}

	/**
	 * Render one project as plain text.
	 *
	 * @param array $project Validated project.
	 * @return string
	 */
	public static function to_text( array $project ) {
		$lines = array();

		$lines[] = 'DESIGN PROJECT GENERATOR';
		$lines[] = str_repeat( '=', 60 );
		$lines[] = '';

		$field = static function ( $label, $value ) use ( &$lines ) {
			if ( '' === trim( (string) $value ) ) {
				return;
			}
			$lines[] = strtoupper( $label ) . ':';
			$lines[] = (string) $value;
			$lines[] = '';
		};

		$list = static function ( $label, $items ) use ( &$lines ) {
			$items = array_filter( (array) $items );
			if ( empty( $items ) ) {
				return;
			}
			$lines[] = strtoupper( $label ) . ':';
			foreach ( $items as $item ) {
				$lines[] = '- ' . $item;
			}
			$lines[] = '';
		};

		$get = static function ( $key ) use ( $project ) {
			return isset( $project[ $key ] ) ? $project[ $key ] : '';
		};

		$field( __( 'Project ID', 'design-project-generator' ), $get( 'id' ) );
		$field( __( 'Project', 'design-project-generator' ), $get( 'title' ) );
		$field( __( 'Category', 'design-project-generator' ), $get( 'category' ) . ' / ' . $get( 'project_type' ) );
		$field( __( 'Difficulty', 'design-project-generator' ), ucfirst( (string) $get( 'difficulty' ) ) );
		$field(
			__( 'Estimated time', 'design-project-generator' ),
			self::format_minutes( (int) $get( 'estimated_time' ) )
		);
		$field( __( 'Client', 'design-project-generator' ), $get( 'client' ) );
		$field( __( 'Industry', 'design-project-generator' ), $get( 'industry' ) );
		$field( __( 'Background', 'design-project-generator' ), $get( 'background' ) );
		$field( __( 'Objective', 'design-project-generator' ), $get( 'objective' ) );
		$field( __( 'Target audience', 'design-project-generator' ), $get( 'audience' ) );
		$field( __( 'Design direction', 'design-project-generator' ), trim( $get( 'style' ) . '. ' . $get( 'style_direction' ) ) );
		$field( __( 'Colour direction', 'design-project-generator' ), $get( 'color_direction' ) );
		$field( __( 'Typography direction', 'design-project-generator' ), trim( $get( 'typography' ) . ' ' . $get( 'typography_note' ) ) );
		$field( __( 'Brand personality', 'design-project-generator' ), $get( 'personality' ) );
		$field( __( 'Budget', 'design-project-generator' ), $get( 'budget' ) );
		$field( __( 'Deadline', 'design-project-generator' ), $get( 'deadline' ) );

		$palette = isset( $project['palette']['colors'] ) ? $project['palette']['colors'] : array();

		if ( ! empty( $palette ) ) {
			$swatches = array();
			foreach ( $palette as $role => $hex ) {
				$swatches[] = ucfirst( $role ) . ' ' . strtoupper( $hex );
			}
			$list( __( 'Colour palette', 'design-project-generator' ), $swatches );
		}

		$list( __( 'Required content', 'design-project-generator' ), $get( 'content' ) );
		$list( __( 'Deliverables', 'design-project-generator' ), $get( 'deliverables' ) );
		$list( __( 'Restrictions', 'design-project-generator' ), $get( 'restrictions' ) );
		$list( __( 'Competitors', 'design-project-generator' ), $get( 'competitors' ) );
		$list( __( 'Success criteria', 'design-project-generator' ), $get( 'success' ) );

		if ( ! empty( $project['challenge']['prompt'] ) ) {
			$challenge = $project['challenge']['name'] . ' — ' . $project['challenge']['prompt'];

			if ( ! empty( $project['challenge']['duration'] ) ) {
				$challenge .= ' (' . self::format_minutes( (int) round( $project['challenge']['duration'] / 60 ) ) . ')';
			}

			$field( __( 'Challenge', 'design-project-generator' ), $challenge );
		}

		$lines[] = str_repeat( '-', 60 );
		$lines[] = sprintf(
			/* translators: %s: site name. */
			__( 'Generated by Design Project Generator on %s', 'design-project-generator' ),
			get_bloginfo( 'name' )
		);

		return implode( "\n", $lines ) . "\n";
	}

	/**
	 * Render an assignment as plain text.
	 *
	 * @param array $assignment Assignment payload.
	 * @return string
	 */
	public static function assignment_to_text( array $assignment ) {
		$lines   = array();
		$lines[] = 'DESIGN PROJECT GENERATOR — ' . strtoupper( __( 'Assignment', 'design-project-generator' ) );
		$lines[] = str_repeat( '=', 60 );
		$lines[] = '';
		$lines[] = $assignment['title'];
		$lines[] = '';

		foreach ( (array) $assignment['settings'] as $key => $value ) {
			if ( is_scalar( $value ) && '' !== (string) $value ) {
				$lines[] = ucfirst( str_replace( '_', ' ', (string) $key ) ) . ': ' . $value;
			}
		}

		$lines[] = '';

		foreach ( $assignment['projects'] as $index => $project ) {
			$lines[] = str_repeat( '=', 60 );
			$lines[] = sprintf(
				/* translators: 1: student number, 2: project identifier. */
				__( 'STUDENT %1$02d — %2$s', 'design-project-generator' ),
				$index + 1,
				$project['id']
			);
			$lines[] = str_repeat( '=', 60 );
			$lines[] = '';
			$lines[] = self::to_text( $project );
		}

		return implode( "\n", $lines );
	}

	/**
	 * Format a number of minutes for humans.
	 *
	 * @param int $minutes Minutes.
	 * @return string
	 */
	public static function format_minutes( $minutes ) {
		$minutes = max( 0, (int) $minutes );

		if ( $minutes < 60 ) {
			/* translators: %d: number of minutes. */
			return sprintf( _n( '%d minute', '%d minutes', $minutes, 'design-project-generator' ), $minutes );
		}

		$hours = floor( $minutes / 60 );
		$rest  = $minutes % 60;

		if ( 0 === $rest ) {
			/* translators: %d: number of hours. */
			return sprintf( _n( '%d hour', '%d hours', $hours, 'design-project-generator' ), $hours );
		}

		return sprintf(
			/* translators: 1: number of hours, 2: number of minutes. */
			__( '%1$dh %2$dm', 'design-project-generator' ),
			$hours,
			$rest
		);
	}

	/**
	 * Serve an assignment as a text download from the admin screens.
	 *
	 * @return void
	 */
	public function handle_assignment_download() {
		$post_id = isset( $_GET['assignment'] ) ? absint( $_GET['assignment'] ) : 0;

		if ( ! $post_id || ! DPG_Security::can_teach() ) {
			wp_die( esc_html__( 'You are not allowed to export this assignment.', 'design-project-generator' ), '', array( 'response' => 403 ) );
		}

		check_admin_referer( 'dpg_export_assignment_' . $post_id );

		$post = get_post( $post_id );

		if ( ! $post || DPG_Post_Types::ASSIGNMENT !== $post->post_type ) {
			wp_die( esc_html__( 'Assignment not found.', 'design-project-generator' ), '', array( 'response' => 404 ) );
		}

		if ( ! DPG_Post_Types::user_owns( $post, get_current_user_id() ) ) {
			wp_die( esc_html__( 'You are not allowed to export this assignment.', 'design-project-generator' ), '', array( 'response' => 403 ) );
		}

		$assignment = DPG_Post_Types::read_assignment( $post );

		if ( ! $assignment ) {
			wp_die( esc_html__( 'Assignment data could not be read.', 'design-project-generator' ), '', array( 'response' => 500 ) );
		}

		$body     = self::assignment_to_text( $assignment );
		$filename = sanitize_file_name( sanitize_title( $assignment['title'] ) . '-assignment.txt' );

		nocache_headers();
		header( 'Content-Type: text/plain; charset=utf-8' );
		header( 'Content-Disposition: attachment; filename="' . $filename . '"' );
		header( 'Content-Length: ' . strlen( $body ) );

		echo $body; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Plain-text download, not HTML.
		exit;
	}
}
